runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /_ah/warmup
  script: _go_app
  login: admin

env_variables:
  PROJECT_ID: 'gallery-67d5b'
  SECRET_PATH: 'secret/client_secret.json'
  TEST_HOST: 'https://dddev.ngrok.io'
  SCOPES: 'email,https://www.googleapis.com/auth/calendar.events.readonly'

inbound_services:
- warmup